### ISSUE TITLE
Is Rails dependency really necessary?

### ISSUE THREAD

**Issue by spijet** [EmCousin/grape_fast_jsonapi#11]
First of all, thank you for this gem. :)

But is it really necessary to pull Rails as a dependency? I see that it's specified as "development" dependency in `gemspec` file, but there's an explicit `require 'rails'` statement in `lib/grape_fast_jsonapi.rb:3`, which prevents it from being used with, for example, Sinatra-based apps.

**Comment by codingjerk** [comment]
`require 'rails'` does not prevent library to be using with Sinatra-based apps tbc, but unnecessary dependency is unnecessary dependency.

**Comment by spijet** [comment]
Actually, yes — I commented out the `require 'rails'` line by hand and it seems to work fine. Haven't checked all the features yet, though. But still, this won't do in a production environment, where gems are pulled in on every deployment.

**Comment by spijet** [comment]
It seems that I was (kinda) mistaken, and the Formatter module uses some ActiveRecord-specific stuff when working with collections, so it may be better to depend on ActiveRecord instead of Rails, unless I miss something else. :)

**Comment by EmCousin** [comment]
Hi @spijet, thanks for your issue. The formatter does use ActiveModel naming and serialization related methods, but only if the object to be serialized actually responds to these methods.

I'm working on a PR to actually remove Rails as a dependency : #12, feel free to check it out and confirm me if it works. Just as well, I am open to suggestions for improvement.

  Thanks!

**Comment by spijet** [comment]
Thanks a lot! I'll check this new branch locally in my app and will let you know if it works. I'll add comments (or even commits, maybe :wink:) in the PR if anything comes up.

Can you hold this issue as open while I test the PR, please?

**Comment by EmCousin** [comment]
@spijet PR merged and gem published to rubygems
