### ISSUE TITLE
[Question] Best way to differentiate serializers that share type?

### ISSUE THREAD

**Issue by rromanchuk** [EmCousin/grape_fast_jsonapi#8]
I'm probably overthinking this, but is there a cleaner way for specifying the serializer when you may have two serializers that share a type?  

Here's standard usage when serializing a `User` instance.
```ruby
#[...]
user = User.last # AR record
render user, { params: { current_user: current_user } }
```

Here's usage when I want to render the typical `User` instance, but using a thinner version of the serializer. Notice how it's a bit anti-pattern, probably because I wasn't sure how to cover this case. 
 
```ruby
#[...]
user = User.last # AR record
jsonapi_options = {}
render CompactUserSerializer.new(user, jsonapi_options).serialized_json
```

Respective serializers below

```ruby
class UserSerializer < BaseSerializer
  include FastJsonapi::ObjectSerializer
  attributes :first_name, :last_name, :name, :bio, :email, :image_url
  
  # More complex/expensive serialization
  attribute :some_other_property do |user|
    user.some_other_property
  end

  attribute :current_user_following do |user, params|
    params[:current_user] ? params[:current_user].follows?(user) : false
  end

  # [...]

end
```

```ruby
class CompactUserSerializer < BaseSerializer
  include FastJsonapi::ObjectSerializer
  set_type :user
  attributes :first_name, :last_name, :name, :bio, :image_url
end
```

This is probably bad practice to begin with because it's definitely not DRY, I wonder if i should just be utilizing `fast_jsonapi`'s conditional attributes and utilize passed params to branch on the same serializer. 

```ruby
#[...]
user = User.last # AR record
render user, { params: { current_user: current_user, compact_version: true } }
```

Could probably also use a combination of mixins to make the serializer more readable

```ruby
module AuthenticatedProperties
  attribute :foo, if: Proc.new { |record, params|
    params[:compact_version] == false
  }

  # [...]
end

class UserSerializer < BaseSerializer
  include FastJsonapi::ObjectSerializer
  include AuthenticatedProperties
  
  attributes :first_name, :last_name, :name, :bio, :image_url
  # [...]
end 
```

**Comment by EmCousin** [comment]
Hi @rromanchuk, there is no cleaner way at the moment. I guess we could develop something that would enable to pass a `serializer` option, overwriting the convention-based default serializer. Like what we can find here : https://github.com/ruby-grape/grape-active_model_serializers#manually-specifying-serializer--adapter-options

I'm not a huge fan personally, I tend to think this gem should remain as minimalistic as possible, but I admit that this is a biased opinion.

I'm still working on finishing the test coverage for this gem at the moment, in the mean time, let me know what you think of this

**Comment by rromanchuk** [comment]
The more I think about it, I agree, i don't think it should be added. It's usually a sign of code smells. 

In fact, what i'm doing is probably a very bad idea and ripe for a lot of issues down the road. 

I can essentially accomplish the same thing with sparse field-sets 
https://github.com/Netflix/fast_jsonapi#sparse-fieldsets
