### ISSUE TITLE
content-type not supported

### ISSUE THREAD

**Issue by waclock** [EmCousin/grape_fast_jsonapi#9]
Hello,

Thanks for the great gem. I'm currently using Grape + this gem, and I'm having some issues regarding the content-type. I can GET without problems, however patching/posting/putting is giving me problems:

`error: "The provided content-type 'application/vnd.api+json' is not supported."`

The CURL I'm doing is the following:
```
curl 'http://localhost:5000/api/v1/users/1' -H 'Origin: http://localhost:3000' -H 'access-token: JB3pVL_Zg5u3zO6V2PsLQg' -H 'client: D8QkWH9542kk9BtnUzZpgQ' -H 'Content-Type: application/vnd.api+json' -H 'Accept: application/vnd.api+json' -H 'expiry: 1554285246' -H 'uid: test@test.com' -H 'Referer: http://localhost:3000/profile' -H 'token-type: Bearer' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36' --data-binary '{"data":{"id":1,"type":"user","attributes":{"test":true}}}' --compressed
```

**Comment by waclock** [comment]
I believe I have managed to fix this issue by adding the following:

```
    content_type :jsonapi, "application/vnd.api+json"
    # format :json
    formatter :json, Grape::Formatter::FastJsonapi
    formatter :jsonapi, Grape::Formatter::FastJsonapi
``` 
I'm not aware of why the `format :json` is needed, but appearently commenting that makes everything work OK.

**Comment by EmCousin** [comment]
Hi @waclock,

> I'm not aware of why the format :json is needed, but appearently commenting that makes everything work OK.

I believe the explanation is [here](https://github.com/ruby-grape/grape#api-formats):
> You can have your API only respond to a single format with `format`. If you use this, the API will **not** respond to file extensions other than specified in `format`.

`format: :json` is actually not needed. It's just one way of defining which formats you accept using Grape. But I guess the Readme can be confusing. I'll see to edit it with a better example

**Comment by waclock** [comment]
Thanks for the quick response.

That makes complete sense, in that case I have a suggestion which is to:
1. FastJsonAPI should respond to JSONAPI standards, and to be JSONAPI-compliant, the formatter should by default pick `"application/vnd.api+json"`, plus, the default formatter should actually be `jsonapi` and not `json`
2. Update the docs to remove the `format :json` from the docs, as I don't think that serves any purpose, is that correct?
